# Hyperparameters shared by all architecture variants we test.

name: ??
# Dataset related parameters
augment: False          # Weather to use data-augmentation of the dataset if the system has symmetries.
# Architectural and Task parameters
equivariant: True      # Impose equivariance constraints on NNs
activation: ReLU
n_layers: 4             # Number MLPs' layers (including input and output layers)

# Optimization hyperparameters parameters
lr: 1e-3
batch_size: 1024


