# Hyperparameters shared by all architecture variants we test.

name: ??
# Dataset related parameters
augment: False          # Weather to use data-augmentation of the dataset if the system has symmetries.
# Architectural and Task parameters
equivariance: False     # Impose equivariance constraints on NNs
activation: ReLU
pred_horizon: 1.0       # Prediction horizon (int) number of time samples (float) percentage of trajectory
obs_dim: 4              # Dimensions of the observation space `m`. Assumed to be a complex valued vector space C^m.
hidden_neurons: 32      # Number of neurons in hidden layers of MLPs
n_layers: 4             # Number MLPs' layers (including input and output layers)

# Optimization hyperparameters parameters
lr: 1e-3
batch_size: 512


