defaults:
  - base_model

name: DAE
# Model hyperparameters
latent_state_pred_w: 4.0                         # Cost function weight for prediction in observation space Z
state_pred_w: 1.0                                # Cost function weight for prediction in state space X
orth_w: 0.0                                      # Weight of the orthonormal regularization term in the loss function

# Optimization hyperparameters parameters
lr: 1e-3
equivariant: False
reuse_input_observable: False
summary: ${model.name}-Z_w:${model.latent_state_pred_w}-Act:${model.activation}-B:${model.bias}-BN:${model.batch_norm}-LR:${model.lr}-L:${model.num_layers}-${model.num_hidden_units}
