defaults:
  - base_model

name: DPNet
# Model hyperparameters
equivariant: False
activation: Identity
n_layers: 2             # Number MLPs' layers (including input and output layers)
batch_norm: False       # Something wrong happens when we turn batch norm on. Performance goes to hell.
bias: False
# Optimization hyperparameters parameters
lr: 1e-3
batch_size: 1024

max_ck_window_length: ${system.pred_horizon}    # Maximum length of the Chapman-Kolmogorov window
ck_w: 0.0                                   # Weight of the Chapman-Kolmogorov regularization term in the loss function
orth_w: 0.1                                 # Weight of the orthonormal regularization term in the loss function
single_obs_space: False                     # Whether to use an auxiliary observable space.
use_spectral_score: True                    # Whether to use the spectral or the correlation score

summary: ${model.name}-Equiv:${model.equivariant}-CK_w:${model.ck_w}-Orth_w:${model.orth_w}-Win:${model.max_ck_window_length}-Act:${model.activation}-B:${model.bias}-BN:${model.batch_norm}-LR:${model.lr}-L:${model.n_layers}-OS:${model.single_obs_space}-SS:${model.use_spectral_score}

