defaults:
  - base_model

name: DPNet
# Model hyperparameters
equivariant: True
activation: ReLU
n_layers: 4             # Number MLPs' layers (including input and output layers)

# Optimization hyperparameters parameters
lr: 1e-3
batch_size: 1024

#eigval_init: "stable"   # Initialization of eigenvalues [stable, ]
#eigval_constraint: "unconstrained"   # [unconstrained or unit_circle]