defaults:
  - base_model

name: DPNet
# Model hyperparameters
equivariant: True
activation: ReLU
n_layers: 4             # Number MLPs' layers (including input and output layers)

# Optimization hyperparameters parameters
lr: 1e-3
batch_size: 1024

max_ck_window_length: 6
ck_w: 1e-2             # Weight of the Chapman-Kolmogorov regularization term in the loss function
orthonormal_w: 5e-3    # Weight of the orthonormal regularization term in the loss function

#eigval_init: "stable"   # Initialization of eigenvalues [stable, ]
#eigval_constraint: "unconstrained"   # [unconstrained or unit_circle]