defaults:
  - dae

name: E-DAE
# Model hyperparameters
obs_pred_w: 1.0                                 # Cost function weight for prediction in observation space Z
orth_w: 0.0                                     # Weight of the orthonormal regularization term in the loss function
corr_w: 0.0

# Optimization hyperparameters parameters
lr: 1e-3
equivariant: True

# Model hyperparameters
state_dependent_obs_dyn: False                  # Whether to use state-dependent observation dynamics
group_avg_trick: True

