defaults:
  - dae

name: E-DAE
# Model hyperparameters
latent_state_pred_w: 4.0                         # Cost function weight for prediction in observation space Z
state_pred_w: 1.0                                # Cost function weight for prediction in state space X
orth_w: 0.0                                      # Weight of the orthonormal regularization term in the loss function

# Optimization hyperparameters parameters
lr: 1e-3
equivariant: True
augment: False

# Latent representation hyperparameter
#rep_Z: regular #  regular | state               # Define the representation of the latent space as multiplicities of the group regular/state representations
